[versions]
agp = "8.13.2"
kotlin = "2.2.21"
coreKtx = "1.15.0"
appcompat = "1.7.0"
material = "1.12.0"
lifecycleService = "2.8.7"
ftpserver = "1.2.1"
slf4j = "1.7.36"
junit = "4.13.2"
commonsNet = "3.11.1"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }
ftpserver-core = { group = "org.apache.ftpserver", name = "ftpserver-core", version.ref = "ftpserver" }
slf4j-android = { group = "org.slf4j", name = "slf4j-android", version.ref = "slf4j" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
commons-net = { group = "commons-net", name = "commons-net", version.ref = "commonsNet" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
